export const JOB_TITLES = [
  "CNC Programmer",
  "Manual Machinist",
  "Tool & Die Maker",
  "CNC Supervisor / Lead Machinist",
  "Injection Mold Operator",
  "SMT Machine Operator",
  "Press Brake Operator",
  "Punch Press Operator",
  "Stamping Press Operator",
  "CNC Waterjet Setup / Operator",
  "Roll Form Machine Operator",
  "Maintenance Mechanic",
  "Maintenance Electrician",
  "Field Service Technician",
  "Maintenance Manager",
  "Electrical Engineer",
  "Robot Technician / Programmer",
  "Electrical Engineering Manager",
  "Mechanical Engineer",
  "Tool & Die Designer",
  "CAD Draftsman / Detailer",
  "Mechanical Engineering Manager",
  "Quality Manager",
  "Quality Engineer ",
  "Quality Inspector",
  "Process Engineer",
  "Welder",
  "Welder / Fitter",
  "Metal Fabricator",
  "Machine Builder",
  "Mechanical Assembler",
  "Electrical Assembler",
  "Panel Builder",
  "CMM Technician / Programmer",
  "CNC Plasma Cutter Setup / Operator",
  "Industrial Electrician",
  "Automation Technician",
  "Material Handler",
  "Manufacturing Engineer",
  "CNC Machinist",
  //   "Tool Room Machinist",
  //   "PLC Programmer",
  //   "Wire EDM Setup / Operator",
  //   "Mechanical Designer",
  //   "Automated Saw Operator",
  //   "Mold Maker",
  //   "Forklift Operator",
  //   "Machine Operator",
  //   "Product Engineering Manager ",
  //   "Controls Engineer",
  //   "CNC Machine Operator",
  //   "CNC Lathe Setup / Operator",
  //   "Swiss CNC Lathe Setup / Operator ",
  //   "Roll Thread Machine Operator",
  //   "Production Supervisor",
  //   "Mold Setup Technician",
  //   "CNC Grinder Setup / Operator",
  //   "Electro-Mechanical Assembler",
  //   "Screw Machine Setup / Operator",
  //   "Operations Manager",
  //   "Lead Machine Builder",
  //   "Project Manager",
  //   "Maintenance Technician",
  //     "Welding Supervisor",
  //     "CNC Mill Setup / Operator",
  //   "Manual Grinder Operator",
  //   "Electrical Designer",
  //   "Quality Technician",
  //   "Robotic Welder Operator",
  //   "Tool Room Supervisor",
  //   "Ram / Sinker EDM Operator",
  //   "Injection Mold Process Technician",
  //   "Cold Forming Machine Operator",
  //   "Boring Mill Machinist",
  //   "Tooling Engineer",
  //   "Automation Engineer",
  //   "CNC Machine Repair Tech",
  //   "Machine Shop Supervisor ",
  //   "Stockroom Technician",
  //   "Manufacturing Supervisor",
  //   "Maintenance Machinist",
  //   "Purchasing Manager",
  //   "Extrusion Machine Operator",
  //   "Wire Bending Machine Operator",
  //   "Automation Engineering Manager",
  //   "Production Planner",
  //   "Turret Punch Press Operator",
  //   "Assistant Manufacturing Supervisor",
  //   "Assistant Technical Manufacturing Supervisor",
  //   "Warehouse Supervisor",
  //   "Supplier Quality Technician",
  //   "CNC Laser Machine Operator",
  //   "Heading Machine Operator",
  //   "CNC Router Setup / Operator",
  //   "Plant Engineer",
  //   "Manufacturing Sales Specialist",
  //   "Compounding Supervisor",
  //   "Conveyor Systems Engineer",
  //   "Wire EDM Machinist",
  //   "CNC Machinist (Lathes)",
  //   "Swiss CNC Machinist",
  //   "Screw Machine Operator",
  //   "CNC Machinist (CNC Mills)",
  //   "Ram / Sinker EDM Machinist",
  //   "Sheet Metal Programmer",
  //   "Multi-Spindle Screw Machine Operator",
  //   "Lead CNC Machinist",
  //   "Lead Surface Grinder",
  //   "Machinist Apprentice",
  //   "Manual Grinder",
  //   "Surface Grinder Operator",
  //   "CNC Setup Machinist",
  //   "Manual Grinder Setup / Operator",
  //   "CNC Boring Mill Machinist",
  //   "Process Technician (Injection Molding)",
  //   "Tooling Design Engineer",
  //   "Tool Crib Attendant",
  //   "Extrusion Blow Molding Process Technician",
  //   "Tool Maker",
  //   "Mold Repair Technician",
  //   "Tooling Technician",
  //   "Process Technician Apprentice",
  //   "Rolled Thread Machine Operator",
  //   "Compound / Color Mixer",
  //   "Warehouse Operations",
  //   "Industrial Painter",
  //   "Overheard Crane Operator",
  //   "Construction Installer",
  //   "Electroplating Technician",
  //   "Manufacturing Data Entry",
  //   "Deburr Operator/ Packaging / Utility",
  //   "General Laborer",
  //   "Industrial Sewer",
  //   "Material Handler / Saw operator",
  //   "Manufacturing Packer",
  //   "Manufacturing Packer (Night Shift)",
  //   "Extrusion Operator",
  //   "Press Operator",
  //   "Printing Press Operator",
  //   "Maintenance Technician - Entry Level",
  //   "CNC Machine Repair Technician",
  //   "CNC Field Service Tech",
  //   "CNC Field Service Trainee",
  //   "Applications Design Engineer",
  //   "Industrial Sales Engineer",
  //   "Senior Mechanical Engineer",
  //   "Robot Programmer",
  //   "Controls Engineer Manager",
  //   "Senior Controls Engineer",
  //   "Senior Controls Engineer (Remote)",
  //   "Manufacturing Software Engineer",
  //   "Project Manager - Automation",
  //   "Manufacturing Software Technician",
  //   "Machine Builder Trainee",
  //   "Assembler",
  //   "Machine Tool Pipe Fitter",
  //   "General Factory",
  //   "Product Assembler",
  //   "Manufacturing Process Engineer",
  //   "Project Engineer",
  //   "Industrial Engineer",
  //   "Test Technician",
  //   "Metallurgical Process Engineer",
  //   "Composites Engineer",
  //   "Production Engineer",
  //   "CMM Programmer",
  //   "Heat Treat Supervisor",
  //   "Lab / Compliance Manager",
  //   "Injection Molding Supervisor",
  //   "Plant Manager",
  //   "Stationary Engineer",
  //   "Lab Technician",
  //   "Continuous Improvement Engineer",
  //   "Metrology Technician",
  //   "Operations Director",
  //   "EHS Manager",
  //   "TIG Welder",
  //   "Sales Applications Engineer",
  //   "Account Manager",
  //   "Customer Service Specialist (Industrial Distributor)",
  //   "Inside Sales Assistant (Industrial)",
  //   "Truck Driver CDL A - Bulk Gases",
  //   "Route Sales Driver",
  //   "Beverage Systems Technician",
  //   "Truck Driver CDL A - Beverage Services",
  //   "IT Support Specialist",
  //   "Machinery Sales Rep",
  //   "Inside Technical Sales Rep",
  //   "Pricing & Contract Manager",
  //   "HR Manager",
  //   "Supply Chain Manager",
  //   "Office Administrator",
  //   "Controller",
  //   "Process Technician",
  //   "Heat Treat Supervisor (Combustion Technician)",
  //   "Lab/Compliance Manager",
  //   "Press Brake Operator",
  //   "Punch Press Operator",
  //   "Stamping Press Operator",
  //   "CNC Waterjet Setup / Operator",
  //   "Roll Form Machine Operator",
  //   "Maintenance Mechanic",
  //   "Maintenance Electrician",
  //   "Field Service Technician",
  //   "Maintenance Manager",
  //   "Electrical Engineer",
  //   "Robot Technician / Programmer",
  //   "Electrical Engineering Manager",
  //   "Mechanical Engineer",
  //   "Tool & Die Designer",
  //   "CAD Draftsman / Detailer",
  //   "Mechanical Engineering Manager",
  //   "Quality Manager",
  //   "Quality Engineer ",
  //   "Quality Inspector",
  //   "Process Engineer",
  //   "Welder",
  //   "Welder / Fitter",
  //   "Metal Fabricator",
  //   "Machine Builder",
  //   "Mechanical Assembler",
  //   "Electrical Assembler",
  //   "Panel Builder",
  //   "CMM Technician / Programmer",
  //   "CNC Plasma Cutter Setup / Operator",
  //   "Industrial Electrician",
  //   "Automation Technician",
  //   "Material Handler",
  //   "Manufacturing Engineer",
  //   "CNC Machinist",
  //   "Tool Room Machinist",
  //   "PLC Programmer",
  //   "Wire EDM Setup / Operator",
  //   "Mechanical Designer",
  //   "Automated Saw Operator",
  //   "Mold Maker",
  //   "Forklift Operator",
  //   "Machine Operator",
  //   "Product Engineering Manager ",
  //   "Controls Engineer",
  //   "CNC Machine Operator",
  //   "CNC Lathe Setup / Operator",
  //   "Swiss CNC Lathe Setup / Operator ",
  //   "Roll Thread Machine Operator",
  //   "Production Supervisor",
  //   "Mold Setup Technician",
  //   "CNC Grinder Setup / Operator",
  //   "Electro-Mechanical Assembler",
  //   "Screw Machine Setup / Operator",
  //   "Operations Manager",
  //   "Lead Machine Builder",
  //   "Project Manager",
  //   "Maintenance Technician",
  //   "Welding Supervisor",
  //   "CNC Mill Setup / Operator",
  //   "Manual Grinder Operator",
  //   "Electrical Designer",
  //   "Quality Technician",
  //   "Robotic Welder Operator",
  //   "Tool Room Supervisor",
  //   "Ram / Sinker EDM Operator",
  //   "Injection Mold Process Technician",
  //   "Cold Forming Machine Operator",
  //   "Boring Mill Machinist",
  //   "Tooling Engineer",
  //   "Automation Engineer",
  //   "CNC Machine Repair Tech",
  //   "Machine Shop Supervisor ",
  //   "Stockroom Technician",
  //   "Manufacturing Supervisor",
  //   "Maintenance Machinist",
  //   "Purchasing Manager",
  //   "Extrusion Machine Operator",
  //   "Wire Bending Machine Operator",
  //   "Automation Engineering Manager",
  //   "Production Planner",
  //   "Turret Punch Press Operator",
  //   "Assistant Manufacturing Supervisor",
  //   "Assistant Technical Manufacturing Supervisor",
  //   "Warehouse Supervisor",
  //   "Supplier Quality Technician",
  //   "CNC Laser Machine Operator",
  //   "Heading Machine Operator",
  //   "CNC Router Setup / Operator",
  //   "Plant Engineer",
  //   "Manufacturing Sales Specialist",
  //   "Compounding Supervisor",
  //   "Conveyor Systems Engineer",
  //   "Wire EDM Machinist",
  //   "CNC Machinist (Lathes)",
  //   "Swiss CNC Machinist",
  //   "Screw Machine Operator",
  //   "CNC Machinist (CNC Mills)",
  //   "Ram / Sinker EDM Machinist",
  //   "Sheet Metal Programmer",
  //   "Multi-Spindle Screw Machine Operator",
  //   "Lead CNC Machinist",
  //   "Lead Surface Grinder",
  //   "Machinist Apprentice",
  //   "Manual Grinder",
  //   "Surface Grinder Operator",
  //   "CNC Setup Machinist",
  //   "Manual Grinder Setup / Operator",
  //   "CNC Boring Mill Machinist",
  //   "Process Technician (Injection Molding)",
  //   "Tooling Design Engineer",
  //   "Tool Crib Attendant",
  //   "Extrusion Blow Molding Process Technician",
  //   "Tool Maker",
  //   "Mold Repair Technician",
  //   "Tooling Technician",
  //   "Process Technician Apprentice",
  //   "Rolled Thread Machine Operator",
  //   "Compound / Color Mixer",
  //   "Warehouse Operations",
  //   "Industrial Painter",
  //   "Overheard Crane Operator",
  //   "Construction Installer",
  //   "Electroplating Technician",
  //   "Manufacturing Data Entry",
  //   "Deburr Operator/ Packaging / Utility",
  //   "General Laborer",
  //   "Industrial Sewer",
  //   "Material Handler / Saw operator",
  //   "Manufacturing Packer",
  //   "Manufacturing Packer (Night Shift)",
  //   "Extrusion Operator",
  //   "Press Operator",
  //   "Printing Press Operator",
  //   "Maintenance Technician - Entry Level",
  //   "CNC Machine Repair Technician",
  //   "CNC Field Service Tech",
  //   "CNC Field Service Trainee",
  //   "Applications Design Engineer",
  //   "Industrial Sales Engineer",
  //   "Senior Mechanical Engineer",
  //   "Robot Programmer",
  //   "Controls Engineer Manager",
  //   "Senior Controls Engineer",
  //   "Senior Controls Engineer (Remote)",
  //   "Manufacturing Software Engineer",
  //   "Project Manager - Automation",
  //   "Manufacturing Software Technician",
  //   "Machine Builder Trainee",
  //   "Assembler",
  //   "Machine Tool Pipe Fitter",
  //   "General Factory",
  //   "Product Assembler",
  //   "Manufacturing Process Engineer",
  //   "Project Engineer",
  //   "Industrial Engineer",
  //   "Test Technician",
  //   "Metallurgical Process Engineer",
  //   "Composites Engineer",
  //   "Production Engineer",
  //   "CMM Programmer",
  //   "Heat Treat Supervisor",
  //   "Lab / Compliance Manager",
  //   "Injection Molding Supervisor",
  //   "Plant Manager",
  //   "Stationary Engineer",
  //   "Lab Technician",
  //   "Continuous Improvement Engineer",
  //   "Metrology Technician",
  //   "Operations Director",
  //   "EHS Manager",
  //   "TIG Welder",
  //   "Sales Applications Engineer",
  //   "Account Manager",
  //   "Customer Service Specialist (Industrial Distributor)",
  //   "Inside Sales Assistant (Industrial)",
  //   "Truck Driver CDL A - Bulk Gases",
  //   "Route Sales Driver",
  //   "Beverage Systems Technician",
  //   "Truck Driver CDL A - Beverage Services",
  //   "IT Support Specialist",
  //   "Machinery Sales Rep",
  //   "Inside Technical Sales Rep",
  //   "Pricing & Contract Manager",
  //   "HR Manager",
  //   "Supply Chain Manager",
  //   "Office Administrator",
  //   "Controller",
  //   "Process Technician",
  //   "Heat Treat Supervisor (Combustion Technician)",
  //   "Lab/Compliance Manager",
];
